name: build

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - '.github/workflows/build.yml'
  #    - 'transport/internet/tcp/sockopt_darwin.go'
  #schedule:
  #  - cron: '3 * * * *'
    
jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - id: check_version
        run: |
          upstream_version=$(basename $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/v2fly/v2ray-core/releases/latest))
          release_version=$(curl -Ls https://raw.githubusercontent.com/goofw/homebrew-homebrew/v2ray/VERSION)
          [ "$upstream_version" != "$release_version" ] && echo '::set-output name=RUN::true' || echo '::set-output name=RUN::false'
          echo "VERSION=$upstream_version" >> $GITHUB_ENV
      
      - if: steps.check_version.outputs.RUN == 'true'
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      
      - if: steps.check_version.outputs.RUN == 'true'
        uses: actions/checkout@v2
        with:
          repository: v2fly/v2ray-core
          ref: ${{ env.VERSION }}
          path: build
          
      - if: steps.check_version.outputs.RUN == 'true'
        uses: actions/checkout@v2
        with:
          ref: v2ray
          
      - if: steps.check_version.outputs.RUN == 'true'
        run: |
          cp transport/internet/tcp/sockopt_darwin.go build/transport/internet/tcp/sockopt_darwin.go
          sed -i '1s/$/,!darwin/' transport/internet/tcp/sockopt_other.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o v2ray -trimpath -ldflags "-s -w -buildid=" build/main
          
          wget https://github.com/v2fly/v2ray-core/releases/download/$VERSION/v2ray-macos-64.zip
          zip -9vr v2ray-macos-64.zip v2ray
          echo $VERSION > VERSION
          
          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')
          git add v2ray-macos-64.zip VERSION
          git diff-index --quiet HEAD || git commit -m "Update v2ray $VERSION"
          git push
